INSERT INTO country(code, name, nationality) VALUES ('af', 'Afghanistan', 'Afghan');
INSERT INTO country(code, name, nationality) VALUES ('al', 'Albania', 'Albanian');
INSERT INTO country(code, name, nationality) VALUES ('dz', 'Algeria', 'Algerian');
INSERT INTO country(code, name, nationality) VALUES ('ad', 'Andorra', 'Andorran');
INSERT INTO country(code, name, nationality) VALUES ('ai', 'Anguilla', 'Angolan');
INSERT INTO country(code, name, nationality) VALUES ('ar', 'Argentina', 'Argentinean');
INSERT INTO country(code, name, nationality) VALUES ('am', 'Armenia', 'Armenian');
INSERT INTO country(code, name, nationality) VALUES ('aw', 'Aruba', 'Aruban');
INSERT INTO country(code, name, nationality) VALUES ('au', 'Australia', 'Australian');
INSERT INTO country(code, name, nationality) VALUES ('at', 'Austria', 'Austrian');
INSERT INTO country(code, name, nationality) VALUES ('az', 'Azerbaijan', 'Azerbaijani');
INSERT INTO country(code, name, nationality) VALUES ('bs', 'Bahamas', 'Bahamian');
INSERT INTO country(code, name, nationality) VALUES ('bh', 'Bahrain', 'Bahraini');
INSERT INTO country(code, name, nationality) VALUES ('bd', 'Bangladesh', 'Bangladeshi');
INSERT INTO country(code, name, nationality) VALUES ('bb', 'Barbados', 'Barbadian');
INSERT INTO country(code, name, nationality) VALUES ('by', 'Belarus', 'Belarusian');
INSERT INTO country(code, name, nationality) VALUES ('be', 'Belgium', 'Belgian');
INSERT INTO country(code, name, nationality) VALUES ('bz', 'Belize', 'Belizean');
INSERT INTO country(code, name, nationality) VALUES ('bj', 'Benin', 'Beninese');
INSERT INTO country(code, name, nationality) VALUES ('bm', 'Bermuda', 'Bermudian');
INSERT INTO country(code, name, nationality) VALUES ('bt', 'Bhutan', 'Bhutanese');
INSERT INTO country(code, name, nationality) VALUES ('ba', 'Bosnia and Herzegovina', 'Herzegovinian');
INSERT INTO country(code, name, nationality) VALUES ('br', 'Brazil', 'Brazilian');
INSERT INTO country(code, name, nationality) VALUES ('bn', 'Brunei Darussalam', 'Bruneian');
INSERT INTO country(code, name, nationality) VALUES ('bg', 'Bulgaria', 'Bulgarian');
INSERT INTO country(code, name, nationality) VALUES ('bf', 'Burkina Faso', 'Burkinabe');
INSERT INTO country(code, name, nationality) VALUES ('bi', 'Burundi', 'Burundian');
INSERT INTO country(code, name, nationality) VALUES ('kh', 'Cambodia', 'Cambodian');
INSERT INTO country(code, name, nationality) VALUES ('cm', 'Cameroon', 'Cameroonian');
INSERT INTO country(code, name, nationality) VALUES ('ca', 'Canada', 'Canadian');
INSERT INTO country(code, name, nationality) VALUES ('cv', 'Cape Verde', 'Cape Verdean');
INSERT INTO country(code, name, nationality) VALUES ('cf', 'Central African Republic', 'Central African');
INSERT INTO country(code, name, nationality) VALUES ('td', 'Chad', 'Chadian');
INSERT INTO country(code, name, nationality) VALUES ('cl', 'Chile', 'Chilean');
INSERT INTO country(code, name, nationality) VALUES ('cn', 'China', 'Chinese');
INSERT INTO country(code, name, nationality) VALUES ('co', 'Colombia', 'Colombian');
INSERT INTO country(code, name, nationality) VALUES ('km', 'Comoros', 'Comoran');
INSERT INTO country(code, name, nationality) VALUES ('cg', 'Congo', 'Congolese');
INSERT INTO country(code, name, nationality) VALUES ('cr', 'Costa Rica', 'Costa Rican');
INSERT INTO country(code, name, nationality) VALUES ('hr', 'Croatia (Hrvatska)', 'Croatian');
INSERT INTO country(code, name, nationality) VALUES ('cu', 'Cuba', 'Cuban');
INSERT INTO country(code, name, nationality) VALUES ('cy', 'Cyprus', 'Cypriot');
INSERT INTO country(code, name, nationality) VALUES ('cz', 'Czech Republic', 'Czech');
INSERT INTO country(code, name, nationality) VALUES ('dk', 'Denmark', 'Danish');
INSERT INTO country(code, name, nationality) VALUES ('dj', 'Djibouti', 'Djibouti');
INSERT INTO country(code, name, nationality) VALUES ('dm', 'Dominica', 'Dominican');
INSERT INTO country(code, name, nationality) VALUES ('ec', 'Ecuador', 'Ecuadorean');
INSERT INTO country(code, name, nationality) VALUES ('eg', 'Egypt', 'Egyptian');
INSERT INTO country(code, name, nationality) VALUES ('sv', 'El Salvador', 'Salvadoran');
INSERT INTO country(code, name, nationality) VALUES ('gq', 'Equatorial Guinea', 'Equatorial Guinean');
INSERT INTO country(code, name, nationality) VALUES ('er', 'Eritrea', 'Eritrean');
INSERT INTO country(code, name, nationality) VALUES ('ee', 'Estonia', 'Estonian');
INSERT INTO country(code, name, nationality) VALUES ('et', 'Ethiopia', 'Ethiopian');
INSERT INTO country(code, name, nationality) VALUES ('fj', 'Fiji', 'Fijian');
INSERT INTO country(code, name, nationality) VALUES ('fi', 'Finland', 'Finnish');
INSERT INTO country(code, name, nationality) VALUES ('fr', 'France', 'French');
INSERT INTO country(code, name, nationality) VALUES ('ga', 'Gabon', 'Gabonese');
INSERT INTO country(code, name, nationality) VALUES ('gm', 'Gambia', 'Gambian');
INSERT INTO country(code, name, nationality) VALUES ('ge', 'Georgia', 'Georgian');
INSERT INTO country(code, name, nationality) VALUES ('de', 'Germany', 'German');
INSERT INTO country(code, name, nationality) VALUES ('gh', 'Ghana', 'Ghanaian');
INSERT INTO country(code, name, nationality) VALUES ('gr', 'Greece', 'Greek');
INSERT INTO country(code, name, nationality) VALUES ('gd', 'Grenada', 'Grenadian');
INSERT INTO country(code, name, nationality) VALUES ('gt', 'Guatemala', 'Guatemalan');
INSERT INTO country(code, name, nationality) VALUES ('gn', 'Guinea', 'Guinean');
INSERT INTO country(code, name, nationality) VALUES ('gw', 'Guinea-Bissau', 'Guinea-Bissauan');
INSERT INTO country(code, name, nationality) VALUES ('gy', 'Guyana', 'Guyanese');
INSERT INTO country(code, name, nationality) VALUES ('ht', 'Haiti', 'Haitian');
INSERT INTO country(code, name, nationality) VALUES ('hn', 'Honduras', 'Honduran');
INSERT INTO country(code, name, nationality) VALUES ('hu', 'Hungary', 'Hungarian');
INSERT INTO country(code, name, nationality) VALUES ('is', 'Iceland', 'Icelander');
INSERT INTO country(code, name, nationality) VALUES ('in', 'India', 'Indian');
INSERT INTO country(code, name, nationality) VALUES ('id', 'Indonesia', 'Indonesian');
INSERT INTO country(code, name, nationality) VALUES ('ir', 'Iran', 'Iranian');
INSERT INTO country(code, name, nationality) VALUES ('iq', 'Iraq', 'Iraqi');
INSERT INTO country(code, name, nationality) VALUES ('ie', 'Ireland', 'Irish');
INSERT INTO country(code, name, nationality) VALUES ('it', 'Italy', 'Italian');
INSERT INTO country(code, name, nationality) VALUES ('jm', 'Jamaica', 'Jamaican');
INSERT INTO country(code, name, nationality) VALUES ('jp', 'Japan', 'Japanese');
INSERT INTO country(code, name, nationality) VALUES ('jo', 'Jordan', 'Jordanian');
INSERT INTO country(code, name, nationality) VALUES ('kz', 'Kazakhstan', 'Kazakhstani');
INSERT INTO country(code, name, nationality) VALUES ('ke', 'Kenya', 'Kenyan');
INSERT INTO country(code, name, nationality) VALUES ('kp', 'Korea (North)', 'North Korean');
INSERT INTO country(code, name, nationality) VALUES ('kr', 'Korea (South)', 'South Korean');
INSERT INTO country(code, name, nationality) VALUES ('kw', 'Kuwait', 'Kuwaiti');
INSERT INTO country(code, name, nationality) VALUES ('kg', 'Kyrgyzstan', 'Kyrgyz');
INSERT INTO country(code, name, nationality) VALUES ('la', 'Laos', 'Laotian');
INSERT INTO country(code, name, nationality) VALUES ('lv', 'Latvia', 'Latvian');
INSERT INTO country(code, name, nationality) VALUES ('lb', 'Lebanon', 'Lebanese');
INSERT INTO country(code, name, nationality) VALUES ('lr', 'Liberia', 'Liberian');
INSERT INTO country(code, name, nationality) VALUES ('ly', 'Libya', 'Libyan');
INSERT INTO country(code, name, nationality) VALUES ('li', 'Liechtenstein', 'Liechtensteiner');
INSERT INTO country(code, name, nationality) VALUES ('lt', 'Lithuania', 'Lithuanian');
INSERT INTO country(code, name, nationality) VALUES ('lu', 'Luxembourg', 'Luxembourger');
INSERT INTO country(code, name, nationality) VALUES ('mk', 'Macedonia', 'Macedonian');
INSERT INTO country(code, name, nationality) VALUES ('mg', 'Madagascar', 'Malagasy');
INSERT INTO country(code, name, nationality) VALUES ('mw', 'Malawi', 'Malawian');
INSERT INTO country(code, name, nationality) VALUES ('my', 'Malaysia', 'Malaysian');
INSERT INTO country(code, name, nationality) VALUES ('mv', 'Maldives', 'Maldivan');
INSERT INTO country(code, name, nationality) VALUES ('ml', 'Mali', 'Malian');
INSERT INTO country(code, name, nationality) VALUES ('mt', 'Malta', 'Maltese');
INSERT INTO country(code, name, nationality) VALUES ('mh', 'Marshall Islands', 'Marshallese');
INSERT INTO country(code, name, nationality) VALUES ('mr', 'Mauritania', 'Mauritanian');
INSERT INTO country(code, name, nationality) VALUES ('mu', 'Mauritius', 'Mauritian');
INSERT INTO country(code, name, nationality) VALUES ('mx', 'Mexico', 'Mexican');
INSERT INTO country(code, name, nationality) VALUES ('md', 'Moldova', 'Moldovan');
INSERT INTO country(code, name, nationality) VALUES ('mc', 'Monaco', 'Monacan');
INSERT INTO country(code, name, nationality) VALUES ('mn', 'Mongolia', 'Mongolian');
INSERT INTO country(code, name, nationality) VALUES ('ma', 'Morocco', 'Moroccan');
INSERT INTO country(code, name, nationality) VALUES ('mz', 'Mozambique', 'Mozambican');
INSERT INTO country(code, name, nationality) VALUES ('na', 'Namibia', 'Namibian');
INSERT INTO country(code, name, nationality) VALUES ('nr', 'Nauru', 'Nauruan');
INSERT INTO country(code, name, nationality) VALUES ('np', 'Nepal', 'Nepalese');
INSERT INTO country(code, name, nationality) VALUES ('nl', 'Netherlands', 'Dutch');
INSERT INTO country(code, name, nationality) VALUES ('nz', 'New Zealand (Aotearoa)', 'New Zealander');
INSERT INTO country(code, name, nationality) VALUES ('ni', 'Nicaragua', 'Nicaraguan');
INSERT INTO country(code, name, nationality) VALUES ('ne', 'Niger', 'Nigerien');
INSERT INTO country(code, name, nationality) VALUES ('no', 'Norway', 'Norwegian');
INSERT INTO country(code, name, nationality) VALUES ('om', 'Oman', 'Omani');
INSERT INTO country(code, name, nationality) VALUES ('pk', 'Pakistan', 'Pakistani');
INSERT INTO country(code, name, nationality) VALUES ('pw', 'Palau', 'Palauan');
INSERT INTO country(code, name, nationality) VALUES ('ps', 'Palestinian Territory', 'Palestinian');
INSERT INTO country(code, name, nationality) VALUES ('pa', 'Panama', 'Panamanian');
INSERT INTO country(code, name, nationality) VALUES ('pg', 'Papua New Guinea', 'Papua New Guinean');
INSERT INTO country(code, name, nationality) VALUES ('py', 'Paraguay', 'Paraguayan');
INSERT INTO country(code, name, nationality) VALUES ('pe', 'Peru', 'Peruvian');
INSERT INTO country(code, name, nationality) VALUES ('pl', 'Poland', 'Polish');
INSERT INTO country(code, name, nationality) VALUES ('pt', 'Portugal', 'Portuguese');
INSERT INTO country(code, name, nationality) VALUES ('qa', 'Qatar', 'Qatari');
INSERT INTO country(code, name, nationality) VALUES ('ro', 'Romania', 'Romanian');
INSERT INTO country(code, name, nationality) VALUES ('ru', 'Russian Federation', 'Russian');
INSERT INTO country(code, name, nationality) VALUES ('rw', 'Rwanda', 'Rwandan');
INSERT INTO country(code, name, nationality) VALUES ('lc', 'Saint Lucia', 'Saint Lucian');
INSERT INTO country(code, name, nationality) VALUES ('ws', 'Samoa', 'Samoan');
INSERT INTO country(code, name, nationality) VALUES ('sm', 'San Marino', 'San Marinese');
INSERT INTO country(code, name, nationality) VALUES ('st', 'Sao Tome and Principe', 'Sao Tomean');
INSERT INTO country(code, name, nationality) VALUES ('sa', 'Saudi Arabia', 'Saudi');
INSERT INTO country(code, name, nationality) VALUES ('sn', 'Senegal', 'Senegalese');
INSERT INTO country(code, name, nationality) VALUES ('sc', 'Seychelles', 'Seychellois');
INSERT INTO country(code, name, nationality) VALUES ('sl', 'Sierra Leone', 'Sierra Leonean');
INSERT INTO country(code, name, nationality) VALUES ('sg', 'Singapore', 'Singaporean');
INSERT INTO country(code, name, nationality) VALUES ('sk', 'Slovakia', 'Slovakian');
INSERT INTO country(code, name, nationality) VALUES ('si', 'Slovenia', 'Slovenian');
INSERT INTO country(code, name, nationality) VALUES ('sb', 'Solomon Islands', 'Solomon Islander');
INSERT INTO country(code, name, nationality) VALUES ('so', 'Somalia', 'Somali');
INSERT INTO country(code, name, nationality) VALUES ('za', 'South Africa', 'South African');
INSERT INTO country(code, name, nationality) VALUES ('es', 'Spain', 'Spanish');
INSERT INTO country(code, name, nationality) VALUES ('lk', 'Sri Lanka', 'Sri Lankan');
INSERT INTO country(code, name, nationality) VALUES ('sd', 'Sudan', 'Sudanese');
INSERT INTO country(code, name, nationality) VALUES ('sr', 'Suriname', 'Surinamer');
INSERT INTO country(code, name, nationality) VALUES ('sz', 'Swaziland', 'Swazi');
INSERT INTO country(code, name, nationality) VALUES ('se', 'Sweden', 'Swedish');
INSERT INTO country(code, name, nationality) VALUES ('ch', 'Switzerland', 'Swiss');
INSERT INTO country(code, name, nationality) VALUES ('sy', 'Syria', 'Syrian');
INSERT INTO country(code, name, nationality) VALUES ('tw', 'Taiwan', 'Taiwanese');
INSERT INTO country(code, name, nationality) VALUES ('tj', 'Tajikistan', 'Tajik');
INSERT INTO country(code, name, nationality) VALUES ('tz', 'Tanzania', 'Tanzanian');
INSERT INTO country(code, name, nationality) VALUES ('th', 'Thailand', 'Thai');
INSERT INTO country(code, name, nationality) VALUES ('tg', 'Togo', 'Togolese');
INSERT INTO country(code, name, nationality) VALUES ('to', 'Tonga', 'Tongan');
INSERT INTO country(code, name, nationality) VALUES ('tt', 'Trinidad and Tobago', 'Trinidadian or Tobagonian');
INSERT INTO country(code, name, nationality) VALUES ('tn', 'Tunisia', 'Tunisian');
INSERT INTO country(code, name, nationality) VALUES ('tr', 'Turkey', 'Turkish');
INSERT INTO country(code, name, nationality) VALUES ('tm', 'Turkmenistan', 'Turkmen');
INSERT INTO country(code, name, nationality) VALUES ('tv', 'Tuvalu', 'Tuvaluan');
INSERT INTO country(code, name, nationality) VALUES ('ug', 'Uganda', 'Ugandan');
INSERT INTO country(code, name, nationality) VALUES ('ua', 'Ukraine', 'Ukrainian');
INSERT INTO country(code, name, nationality) VALUES ('ae', 'United Arab Emirates', 'Emirati');
INSERT INTO country(code, name, nationality) VALUES ('us', 'United States of America', 'American');
INSERT INTO country(code, name, nationality) VALUES ('uy', 'Uruguay', 'Uruguayan');
INSERT INTO country(code, name, nationality) VALUES ('uz', 'Uzbekistan', 'Uzbekistani');
INSERT INTO country(code, name, nationality) VALUES ('ve', 'Venezuela', 'Venezuelan');
INSERT INTO country(code, name, nationality) VALUES ('vn', 'Viet Nam', 'Vietnamese');
INSERT INTO country(code, name, nationality) VALUES ('ye', 'Yemen', 'Yemenite');
INSERT INTO country(code, name, nationality) VALUES ('zm', 'Zambia', 'Zambian');
INSERT INTO country(code, name, nationality) VALUES ('zw', 'Zimbabwe', 'Zimbabwean');
INSERT INTO country(code, name, nationality) VALUES ('bw', 'Botswana', 'Batswana');
INSERT INTO country(code, name, nationality) VALUES ('bo', 'Bolivia', 'Bolivian');
INSERT INTO country(code, name, nationality) VALUES ('gb', 'United Kingdom', 'British');
INSERT INTO country(code, name, nationality) VALUES ('mm', 'Myanmar', 'Burmese');
INSERT INTO country(code, name, nationality) VALUES ('tl', 'Timor-Leste', 'East Timorese');
INSERT INTO country(code, name, nationality) VALUES ('ph', 'Philippines', 'Filipino');
INSERT INTO country(code, name, nationality) VALUES ('ci', 'Côte d''Ivoire', 'Ivorian');
INSERT INTO country(code, name, nationality) VALUES ('fm', 'Micronesia', 'Micronesian');
INSERT INTO country(code, name, nationality) VALUES ('ls', 'Lesotho', 'Mosotho');
INSERT INTO country(code, name, nationality) VALUES ('vu', 'Vanuatu', 'Ni-Vanuatu');
INSERT INTO country(code, name, nationality) VALUES ('rs', 'Serbia', 'Serbian');
